from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AgentSpec:
    """Configuration for one deterministic committee workstream."""

    name: str
    category: str
    weight: float
    focus_components: tuple[str, ...]
    positive: str
    concern: str
    action: str
    role: str = "Institutional diligence workstream"
    sources: tuple[str, ...] = ()


AGENT_SPECS: tuple[AgentSpec, ...] = (
    AgentSpec(
        name='Acquisition Pricing Agent',
        category='acquisition',
        weight=1.4,
        focus_components=('cap_rate', 'cash_on_cash', 'rehab_load', 'data_quality'),
        positive='Pricing has support from yield and basis checks.',
        concern='Pricing may not clear required yield or basis thresholds.',
        action='Refresh seller pricing, closing costs, and maximum offer analysis.',
        role='Institutional diligence workstream: acquisition',
        sources=(
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 10 (DCF and NPV)',
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 10: Capitalization Rate',
        ),
    ),
    AgentSpec(
        name='Purchase Contract Agent',
        category='acquisition',
        weight=0.85,
        focus_components=('data_quality', 'liquidity', 'rehab_load'),
        positive='The contract can be diligenced with identifiable contingencies.',
        concern='The contract package needs stronger contingency and assignment review.',
        action='Review contract dates, contingencies, deposits, and default remedies.',
        role='Institutional diligence workstream: acquisition',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 7 (Real Estate Due Diligence Analysis)',
        ),
    ),
    AgentSpec(
        name='Seller Motivation Agent',
        category='acquisition',
        weight=0.7,
        focus_components=('liquidity', 'market_growth', 'data_quality'),
        positive='Market context may create a negotiation path.',
        concern='Seller motivation is not documented enough to underwrite concessions.',
        action='Document seller timing, competing offers, and retrade tolerance.',
        role='Institutional diligence workstream: acquisition',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 7 (Real Estate Due Diligence Analysis)',
        ),
    ),
    AgentSpec(
        name='Earnest Money Agent',
        category='acquisition',
        weight=0.65,
        focus_components=('data_quality', 'liquidity', 'rehab_load'),
        positive='Deposit exposure appears manageable relative to diligence stage.',
        concern='Deposit risk could become disproportionate without contingency protection.',
        action='Tie earnest money hardening to inspection, financing, and title milestones.',
        role='Institutional diligence workstream: acquisition',
    ),
    AgentSpec(
        name='Closing Costs Agent',
        category='acquisition',
        weight=0.75,
        focus_components=('cash_on_cash', 'data_quality', 'cap_rate'),
        positive='Closing-cost assumptions are within a reviewable range.',
        concern='Closing costs may be under-modeled and dilute initial yield.',
        action='Verify lender fees, title charges, transfer taxes, and escrows.',
        role='Institutional diligence workstream: acquisition',
    ),
    AgentSpec(
        name='Rent Roll Agent',
        category='income',
        weight=1.1,
        focus_components=('vacancy', 'cash_on_cash', 'data_quality'),
        positive='Rent roll supports the income thesis.',
        concern='Rent roll data is insufficient or implies collection risk.',
        action='Reconcile leases, deposits, arrears, move-in dates, and concessions.',
        role='Institutional diligence workstream: income',
        sources=(
            'Fannie Mae Multifamily Guide Part V §401: Lease Audit',
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 5 (Property-Level Pro Forma Analysis)',
        ),
    ),
    AgentSpec(
        name='Lease Audit Agent',
        category='income',
        weight=0.95,
        focus_components=('data_quality', 'vacancy', 'landlord_law'),
        positive='Lease administration risk is reviewable.',
        concern='Lease file gaps could impair collections or legal remedies.',
        action='Audit all leases for term, rent, fees, deposits, occupants, and default rights.',
        role='Institutional diligence workstream: income',
        sources=(
            'Fannie Mae Multifamily Guide Part V §401: Lease Audit',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 30 (Leases and Leasing Strategy)',
        ),
    ),
    AgentSpec(
        name='Loss To Lease Agent',
        category='income',
        weight=0.85,
        focus_components=('market_growth', 'vacancy', 'cash_on_cash'),
        positive='Market context leaves room for rent optimization.',
        concern='Loss-to-lease assumptions may be speculative without comps.',
        action='Build unit-level market rent bridge and renewal plan.',
        role='Institutional diligence workstream: income',
        sources=(
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 30 (Leases and Leasing Strategy)',
        ),
    ),
    AgentSpec(
        name='Market Rent Agent',
        category='income',
        weight=1.15,
        focus_components=('market_growth', 'vacancy', 'data_quality'),
        positive='Rent assumptions align with observable market momentum.',
        concern='Rent assumptions need stronger comp support.',
        action='Refresh rent comps with distance, unit mix, condition, and concession adjustments.',
        role='Institutional diligence workstream: income',
        sources=(
            'U.S. Census Bureau Housing Vacancies and Homeownership (HVS) survey',
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 3 (Market Fundamentals and Rent)',
            'HUD Fair Market Rents (FMR) published rent benchmarks by metro and bedroom count',
        ),
    ),
    AgentSpec(
        name='Ancillary Income Agent',
        category='income',
        weight=0.6,
        focus_components=('cash_on_cash', 'data_quality', 'market_growth'),
        positive='Ancillary income may improve revenue durability.',
        concern='Ancillary income is not substantiated enough to rely on.',
        action='Separate recurring ancillary income from one-time or speculative items.',
        role='Institutional diligence workstream: income',
        sources=(
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 8: Gross Operating Income (Effective Gross Income)',
        ),
    ),
    AgentSpec(
        name='Collection Loss Agent',
        category='income',
        weight=0.85,
        focus_components=('vacancy', 'landlord_law', 'crime'),
        positive='Collection assumptions are within manageable limits.',
        concern='Collection loss could exceed vacancy assumptions in stress.',
        action='Review delinquency history, local eviction timelines, and tenant screening policy.',
        role='Institutional diligence workstream: income',
        sources=(
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 7: Vacancy and Credit Loss',
        ),
    ),
    AgentSpec(
        name='Vacancy Agent',
        category='income',
        weight=1.0,
        focus_components=('vacancy', 'market_growth', 'liquidity'),
        positive='Vacancy risk appears supportable in context.',
        concern='Vacancy could pressure DSCR and cash yield.',
        action='Stress lease-up velocity and downtime by unit type.',
        role='Institutional diligence workstream: income',
        sources=(
            'U.S. Census Bureau Housing Vacancies and Homeownership (HVS) survey',
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 7: Vacancy and Credit Loss',
        ),
    ),
    AgentSpec(
        name='Tax Assessment Agent',
        category='expenses',
        weight=1.05,
        focus_components=('expense_ratio', 'data_quality', 'cap_rate'),
        positive='Tax load is incorporated in the operating model.',
        concern='Tax reassessment may be under-modeled after acquisition.',
        action='Run post-sale assessment and appeal scenarios.',
        role='Institutional diligence workstream: expenses',
        sources=(
            'IRS Publication 527: Residential Rental Property',
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 32: Assessed Value, Property Taxes, and Value Indicated by Assessment',
        ),
    ),
    AgentSpec(
        name='Insurance Market Agent',
        category='expenses',
        weight=1.0,
        focus_components=('expense_ratio', 'crime', 'data_quality'),
        positive='Insurance burden appears manageable under base assumptions.',
        concern='Insurance quotes may reset materially above fixture assumptions.',
        action='Obtain bindable quotes including wind, flood, liability, and ordinance coverage.',
        role='Institutional diligence workstream: expenses',
        sources=(
            'Fannie Mae Multifamily Guide Part V Ch. 5: Property and Liability Insurance',
        ),
    ),
    AgentSpec(
        name='Utilities Agent',
        category='expenses',
        weight=0.7,
        focus_components=('expense_ratio', 'data_quality', 'age'),
        positive='Utility assumptions are reviewable.',
        concern='Utility reimbursement or submetering assumptions need evidence.',
        action='Audit utility bills and tenant reimbursement language.',
        role='Institutional diligence workstream: expenses',
    ),
    AgentSpec(
        name='Repairs And Maintenance Agent',
        category='expenses',
        weight=0.9,
        focus_components=('age', 'expense_ratio', 'rehab_load'),
        positive='Repairs reserve is directionally consistent with age and plan.',
        concern='Maintenance assumptions may be too light for asset age or condition.',
        action='Build a maintenance reserve from inspection and work-order history.',
        role='Institutional diligence workstream: expenses',
        sources=(
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='Capex Reserve Agent',
        category='expenses',
        weight=1.05,
        focus_components=('rehab_load', 'age', 'cash_on_cash'),
        positive='Capital reserve is explicit in the plan.',
        concern='Capex reserve may not absorb component failures.',
        action='Tie reserves to roof, HVAC, plumbing, electrical, parking, and unit-turn schedules.',
        role='Institutional diligence workstream: expenses',
        sources=(
            "Freddie Mac Multifamily Seller/Servicer Guide: replacement reserves at the greater of the engineer's recommendation or $250/unit/year",
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='Payroll Staffing Agent',
        category='expenses',
        weight=0.55,
        focus_components=('expense_ratio', 'data_quality', 'unit_count'),
        positive='Staffing burden appears limited for the asset scale.',
        concern='Payroll or third-party service costs may be omitted.',
        action='Confirm onsite staffing, leasing, maintenance, and bookkeeping assumptions.',
        role='Institutional diligence workstream: expenses',
    ),
    AgentSpec(
        name='Property Management Fee Agent',
        category='expenses',
        weight=0.8,
        focus_components=('expense_ratio', 'vacancy', 'data_quality'),
        positive='Management fee is included in NOI.',
        concern='Management burden could be understated if lease-up is active.',
        action='Obtain a property-management proposal with leasing and renewal fees.',
        role='Institutional diligence workstream: expenses',
        sources=(
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 22: Operating Expense Ratio',
        ),
    ),
    AgentSpec(
        name='HOA And Condo Agent',
        category='expenses',
        weight=0.5,
        focus_components=('expense_ratio', 'data_quality', 'liquidity'),
        positive='Association exposure appears controllable from supplied assumptions.',
        concern='Association dues, reserves, or rental restrictions may be missing.',
        action='Review HOA budget, reserves, minutes, insurance, and rental restrictions.',
        role='Institutional diligence workstream: expenses',
    ),
    AgentSpec(
        name='Expense Benchmark Agent',
        category='expenses',
        weight=1.0,
        focus_components=('expense_ratio', 'data_quality', 'cap_rate'),
        positive='Expense ratio is within benchmarkable territory.',
        concern='Expense ratio may not match property type, age, or market norms.',
        action='Benchmark every operating expense against local comps and historical statements.',
        role='Institutional diligence workstream: expenses',
        sources=(
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 22: Operating Expense Ratio',
        ),
    ),
    AgentSpec(
        name='Rate Curve Agent',
        category='debt',
        weight=1.15,
        focus_components=('dscr', 'ltc', 'cash_on_cash'),
        positive='Debt terms remain workable under the base rate assumption.',
        concern='Rate assumptions create refinancing or payment-shock risk.',
        action='Refresh lender quotes and lock/float strategy before IC approval.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Freddie Mac Multifamily Seller/Servicer Guide',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 17 (Mortgage Basics II: Payments, Yields, and Values)',
        ),
    ),
    AgentSpec(
        name='Debt Yield Agent',
        category='debt',
        weight=1.15,
        focus_components=('dscr', 'cap_rate', 'ltc'),
        positive='Debt yield appears within a lender-reviewable range.',
        concern='Debt yield may be too thin for institutional credit support.',
        action='Compute lender debt yield and resize loan proceeds where necessary.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Fannie Mae Multifamily Underwriting Standards (Form 4660): Tier 2 conventional floor of 1.25x underwritten DSCR / 80% max LTV',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 18 (Commercial Mortgage Analysis and Underwriting)',
        ),
    ),
    AgentSpec(
        name='LTC And LTV Agent',
        category='debt',
        weight=1.05,
        focus_components=('ltc', 'rehab_load', 'data_quality'),
        positive='Leverage does not dominate the thesis.',
        concern='Leverage leaves limited room for cost overruns or value decline.',
        action='Re-cut capitalization with lower proceeds and higher reserve.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Fannie Mae Multifamily Underwriting Standards (Form 4660): Tier 2 conventional floor of 1.25x underwritten DSCR / 80% max LTV',
            'HUD Mortgagee Letter 2025-03 (MAP Guide sizing): market-rate FHA multifamily at 1.15x DSCR / 87% LTV-LTC',
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 26: Loan-to-Value Ratio',
        ),
    ),
    AgentSpec(
        name='Refinance Risk Agent',
        category='debt',
        weight=0.9,
        focus_components=('dscr', 'liquidity', 'market_growth'),
        positive='Refinance and exit options have some support.',
        concern='Takeout financing may be unavailable in a weaker market.',
        action='Stress refinance proceeds at wider spreads and lower appraised value.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 14 (Should You Borrow?)',
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 15 (The Use of Debt and Mortgages)',
        ),
    ),
    AgentSpec(
        name='Interest Rate Cap Agent',
        category='debt',
        weight=0.6,
        focus_components=('dscr', 'cash_on_cash', 'data_quality'),
        positive='Interest-rate protection can be sized if needed.',
        concern='Floating-rate exposure is not mitigated in the current packet.',
        action='Price caps, swaps, or fixed-rate alternatives for floating-rate debt.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Freddie Mac Multifamily Seller/Servicer Guide',
        ),
    ),
    AgentSpec(
        name='Lender Covenants Agent',
        category='debt',
        weight=0.9,
        focus_components=('dscr', 'data_quality', 'ltc'),
        positive='Covenant compliance appears monitorable.',
        concern='Covenant triggers could force cash sweeps or defaults.',
        action='Model DSCR, debt-yield, reserve, reporting, and transfer covenants.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Fannie Mae Multifamily Underwriting Standards (Form 4660): Tier 2 conventional floor of 1.25x underwritten DSCR / 80% max LTV',
            'Freddie Mac Multifamily Seller/Servicer Guide',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 18 (Commercial Mortgage Analysis and Underwriting)',
        ),
    ),
    AgentSpec(
        name='Amortization Agent',
        category='debt',
        weight=0.7,
        focus_components=('dscr', 'cash_on_cash', 'ltc'),
        positive='Amortization is incorporated in cash-flow math.',
        concern='Principal amortization may suppress distributable cash flow.',
        action='Review amortization schedule and interest-only options.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Fannie Mae Multifamily Underwriting Standards (Form 4660): Tier 2 conventional floor of 1.25x underwritten DSCR / 80% max LTV',
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 28: Mortgage Payment/Mortgage Constant',
        ),
    ),
    AgentSpec(
        name='Prepayment Agent',
        category='debt',
        weight=0.55,
        focus_components=('liquidity', 'market_growth', 'data_quality'),
        positive='Prepayment exposure is manageable if exit timing is flexible.',
        concern='Prepayment penalties could impair sale or refinance optionality.',
        action='Verify yield maintenance, defeasance, step-down, and open-period terms.',
        role='Institutional diligence workstream: debt',
        sources=(
            'Freddie Mac Multifamily Seller/Servicer Guide',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 19 (Commercial Mortgage Economics and Investment)',
        ),
    ),
    AgentSpec(
        name='Roof Agent',
        category='physical',
        weight=0.85,
        focus_components=('age', 'rehab_load', 'data_quality'),
        positive='Roof condition can be addressed through capex planning.',
        concern='Roof age or unknown condition may create near-term capital shock.',
        action='Get roof age, useful life, warranty, inspection photos, and replacement quote.',
        role='Institutional diligence workstream: physical',
        sources=(
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='HVAC Agent',
        category='physical',
        weight=0.8,
        focus_components=('age', 'rehab_load', 'expense_ratio'),
        positive='Mechanical systems are captured in the reserve framework.',
        concern='HVAC replacement risk may not be fully reserved.',
        action='Inventory HVAC units, ages, refrigerant type, and replacement costs.',
        role='Institutional diligence workstream: physical',
        sources=(
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='Plumbing Agent',
        category='physical',
        weight=0.8,
        focus_components=('age', 'rehab_load', 'data_quality'),
        positive='Plumbing risk is reviewable through inspections.',
        concern='Hidden plumbing failures could disrupt units and insurance.',
        action='Scope sewer, supply lines, water heaters, and leak history.',
        role='Institutional diligence workstream: physical',
        sources=(
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='Electrical Agent',
        category='physical',
        weight=0.75,
        focus_components=('age', 'rehab_load', 'data_quality'),
        positive='Electrical review can be folded into the capex plan.',
        concern='Electrical obsolescence may raise safety or insurance issues.',
        action='Confirm panels, wiring type, capacity, permits, and code compliance.',
        role='Institutional diligence workstream: physical',
        sources=(
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='Foundation Agent',
        category='physical',
        weight=0.85,
        focus_components=('age', 'rehab_load', 'liquidity'),
        positive='Foundation risk can be diligenced before close.',
        concern='Structural issues could overwhelm the renovation budget.',
        action='Order structural inspection where settlement, water, or cracking is present.',
        role='Institutional diligence workstream: physical',
        sources=(
            'Fannie Mae Multifamily Guide Part V §404: Property Condition Assessment',
        ),
    ),
    AgentSpec(
        name='Environmental Phase I Agent',
        category='physical',
        weight=0.75,
        focus_components=('data_quality', 'crime', 'liquidity'),
        positive='Environmental review can be closed with a standard screen.',
        concern='Environmental diligence is insufficient for final approval.',
        action='Order environmental screen or Phase I where historical use warrants it.',
        role='Institutional diligence workstream: physical',
        sources=(
            'ASTM E1527-21 Phase I Environmental Site Assessment standard',
        ),
    ),
    AgentSpec(
        name='ADA And Fair Housing Agent',
        category='physical',
        weight=0.65,
        focus_components=('data_quality', 'age', 'landlord_law'),
        positive='Accessibility and habitability can be reviewed in closing diligence.',
        concern='Fair-housing or accessibility gaps may create legal exposure.',
        action='Review habitability, accessibility, advertising, screening, and accommodation procedures.',
        role='Institutional diligence workstream: physical',
    ),
    AgentSpec(
        name='Fire Life Safety Agent',
        category='physical',
        weight=0.8,
        focus_components=('age', 'data_quality', 'rehab_load'),
        positive='Life-safety scope can be folded into inspection and capex.',
        concern='Life-safety deficiencies can force immediate capital outlay.',
        action='Verify smoke/CO devices, egress, extinguishers, permits, and local code issues.',
        role='Institutional diligence workstream: physical',
    ),
    AgentSpec(
        name='Renovation Schedule Agent',
        category='physical',
        weight=0.95,
        focus_components=('rehab_load', 'vacancy', 'cash_on_cash'),
        positive='Renovation schedule appears manageable at current scope.',
        concern='Schedule delays could impair lease-up, cash flow, and loan covenants.',
        action='Build a week-by-week construction and unit-turn schedule with float.',
        role='Institutional diligence workstream: physical',
    ),
    AgentSpec(
        name='Renovation Contingency Agent',
        category='physical',
        weight=0.95,
        focus_components=('rehab_load', 'data_quality', 'age'),
        positive='Contingency can be sized to current rehab intensity.',
        concern='Contingency may be inadequate for discovery risk.',
        action='Set contingency based on inspection severity and contractor bid confidence.',
        role='Institutional diligence workstream: physical',
    ),
    AgentSpec(
        name='Population Growth Agent',
        category='market',
        weight=0.85,
        focus_components=('market_growth', 'liquidity', 'vacancy'),
        positive='Population trend supports demand under the base case.',
        concern='Population growth is not strong enough to protect leasing assumptions.',
        action='Refresh census, migration, and household formation signals.',
        role='Institutional diligence workstream: market',
        sources=(
            'U.S. Census Bureau population and housing-unit estimates',
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 8 (Analyzing Metropolitan Long-Term Growth Patterns)',
        ),
    ),
    AgentSpec(
        name='Job Growth Agent',
        category='market',
        weight=0.95,
        focus_components=('market_growth', 'vacancy', 'cash_on_cash'),
        positive='Employment growth supports renter demand.',
        concern='Employment softness could reduce absorption or rent growth.',
        action='Review employer concentration, layoff risk, and wage growth.',
        role='Institutional diligence workstream: market',
        sources=(
            'U.S. Bureau of Labor Statistics: state and metro area employment and wage data',
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 8 (Analyzing Metropolitan Long-Term Growth Patterns)',
        ),
    ),
    AgentSpec(
        name='Wage Growth Agent',
        category='market',
        weight=0.7,
        focus_components=('market_growth', 'school', 'liquidity'),
        positive='Wage growth may support rent affordability.',
        concern='Rent growth could outpace local incomes.',
        action='Compare rents to household income by renter cohort.',
        role='Institutional diligence workstream: market',
        sources=(
            'U.S. Bureau of Labor Statistics: state and metro area employment and wage data',
        ),
    ),
    AgentSpec(
        name='Supply Pipeline Agent',
        category='market',
        weight=1.0,
        focus_components=('vacancy', 'market_growth', 'liquidity'),
        positive='Supply pressure appears manageable in the current market snapshot.',
        concern='New supply could cap rent growth and occupancy.',
        action='Review permits, deliveries, concessions, and submarket inventory.',
        role='Institutional diligence workstream: market',
        sources=(
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 6 (Real Estate Market Analysis)',
            'U.S. Census Bureau Building Permits Survey',
        ),
    ),
    AgentSpec(
        name='Building Permits Agent',
        category='market',
        weight=0.7,
        focus_components=('market_growth', 'vacancy', 'data_quality'),
        positive='Permitting signals are reviewable.',
        concern='Permit activity could imply future supply competition.',
        action='Pull permit trend by property type and census tract.',
        role='Institutional diligence workstream: market',
        sources=(
            'U.S. Census Bureau Building Permits Survey',
        ),
    ),
    AgentSpec(
        name='Absorption Agent',
        category='market',
        weight=0.85,
        focus_components=('vacancy', 'market_growth', 'liquidity'),
        positive='Absorption appears adequate for the unit plan.',
        concern='Absorption risk may delay lease-up.',
        action='Stress days-on-market, concessions, and move-in velocity.',
        role='Institutional diligence workstream: market',
        sources=(
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 6 (Real Estate Market Analysis)',
        ),
    ),
    AgentSpec(
        name='School Quality Agent',
        category='market',
        weight=0.7,
        focus_components=('school', 'liquidity', 'market_growth'),
        positive='School quality provides some demand support.',
        concern='School quality may limit tenant demand or exit buyer pool.',
        action='Confirm school assignments and demand by bedroom count.',
        role='Institutional diligence workstream: market',
    ),
    AgentSpec(
        name='Crime Safety Agent',
        category='market',
        weight=1.0,
        focus_components=('crime', 'vacancy', 'liquidity'),
        positive='Safety indicators are within a manageable band.',
        concern='Safety risk could pressure leasing, collections, and cap rates.',
        action='Review block-level crime, lighting, parking, and property-management controls.',
        role='Institutional diligence workstream: market',
    ),
    AgentSpec(
        name='Transit Access Agent',
        category='market',
        weight=0.65,
        focus_components=('liquidity', 'market_growth', 'vacancy'),
        positive='Access and location can support tenant demand.',
        concern='Weak access could narrow the renter pool.',
        action='Document commute times, transit, parking, and key employment nodes.',
        role='Institutional diligence workstream: market',
    ),
    AgentSpec(
        name='Climate Physical Risk Agent',
        category='market',
        weight=0.9,
        focus_components=('crime', 'insurance', 'data_quality'),
        positive='Physical climate risk can be bounded with insurance and location diligence.',
        concern='Climate, flood, wind, or heat risk may be underwritten too lightly.',
        action='Check flood, wind, wildfire, heat, and insurance availability maps.',
        role='Institutional diligence workstream: market',
        sources=(
            'FEMA National Flood Insurance Program (NFIP) flood maps and flood-zone determinations',
        ),
    ),
    AgentSpec(
        name='Landlord Law Agent',
        category='market',
        weight=0.9,
        focus_components=('landlord_law', 'collection_loss', 'data_quality'),
        positive='Legal environment appears operationally workable.',
        concern='Local landlord law may slow remedies or raise compliance cost.',
        action='Have counsel review eviction, notice, habitability, fee, and rent-control rules.',
        role='Institutional diligence workstream: market',
    ),
    AgentSpec(
        name='Zoning Entitlement Agent',
        category='market',
        weight=0.85,
        focus_components=('data_quality', 'liquidity', 'rehab_load'),
        positive='Zoning questions can be closed with standard diligence.',
        concern='Zoning or use nonconformity could impair operations or exit.',
        action='Obtain zoning letter, certificate of occupancy, and permit history.',
        role='Institutional diligence workstream: market',
    ),
    AgentSpec(
        name='Exit Liquidity Agent',
        category='market',
        weight=1.05,
        focus_components=('liquidity', 'market_growth', 'cap_rate'),
        positive='Exit buyer depth appears reasonable.',
        concern='Exit liquidity may be thin under stress.',
        action='Refresh sale comps, buyer pool, cap-rate sensitivity, and broker opinion.',
        role='Institutional diligence workstream: market',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 18 (Real Estate Owner Exit Strategies)',
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 9 (The Use and Selection of Cap Rates)',
        ),
    ),
    AgentSpec(
        name='Portfolio Concentration Agent',
        category='portfolio',
        weight=0.95,
        focus_components=('liquidity', 'market_growth', 'data_quality'),
        positive='The deal can be sized within concentration limits.',
        concern='Market or strategy concentration may exceed policy.',
        action='Check market, property type, vintage, and operator exposure before allocation.',
        role='Institutional diligence workstream: portfolio',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 15 (Building the Portfolio)',
        ),
    ),
    AgentSpec(
        name='Strategy Fit Agent',
        category='portfolio',
        weight=0.9,
        focus_components=('cap_rate', 'cash_on_cash', 'market_growth'),
        positive='The asset fits a yield-plus-growth rental strategy.',
        concern='The deal may rely on a thesis outside the strategy mandate.',
        action='Map the deal to fund mandate, target return, hold period, and risk budget.',
        role='Institutional diligence workstream: portfolio',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 15 (Building the Portfolio)',
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 4 (Asset Pricing, Portfolio Theory, and Real Estate)',
        ),
    ),
    AgentSpec(
        name='Reserve Liquidity Agent',
        category='portfolio',
        weight=0.9,
        focus_components=('cash_on_cash', 'rehab_load', 'dscr'),
        positive='Reserve planning is visible in the capital plan.',
        concern='Insufficient reserves could force capital calls.',
        action='Size operating, capex, insurance, tax, and debt-service reserves.',
        role='Institutional diligence workstream: portfolio',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 5 (Property-Level Pro Forma Analysis)',
            "Freddie Mac Multifamily Seller/Servicer Guide: replacement reserves at the greater of the engineer's recommendation or $250/unit/year",
        ),
    ),
    AgentSpec(
        name='Sponsor Track Record Agent',
        category='portfolio',
        weight=0.8,
        focus_components=('data_quality', 'liquidity', 'market_growth'),
        positive='Sponsor capability can be underwritten with references.',
        concern='Sponsor execution history is not evidenced in the packet.',
        action='Collect sponsor track record, references, net worth, and liquidity support.',
        role='Institutional diligence workstream: portfolio',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 12 (Real Estate Private Equity: Fund Structure and Cash Flow Distribution)',
        ),
    ),
    AgentSpec(
        name='Property Management Platform Agent',
        category='portfolio',
        weight=0.95,
        focus_components=('vacancy', 'expense_ratio', 'data_quality'),
        positive='Management plan can support ongoing operations.',
        concern='Property-management execution may be the key uncontrolled risk.',
        action='Review manager KPIs, staffing, leasing process, maintenance SLA, and reporting cadence.',
        role='Institutional diligence workstream: portfolio',
    ),
    AgentSpec(
        name='Exit Timing Agent',
        category='portfolio',
        weight=0.75,
        focus_components=('liquidity', 'market_growth', 'dscr'),
        positive='Exit timing has plausible flexibility.',
        concern='Exit timing could collide with debt maturity or market softness.',
        action='Compare hold period against debt maturity, renovation timeline, and cap-rate cycle.',
        role='Institutional diligence workstream: portfolio',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 26 (Real Estate Cycles)',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 27 (Real Options and Land Value)',
        ),
    ),
    AgentSpec(
        name='Return Attribution Agent',
        category='portfolio',
        weight=0.75,
        focus_components=('cap_rate', 'cash_on_cash', 'market_growth'),
        positive='Return drivers are identifiable.',
        concern='Returns may be overly dependent on terminal value expansion.',
        action='Separate yield, rent growth, cap-rate movement, leverage, and renovation alpha.',
        role='Institutional diligence workstream: portfolio',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 17 (Performance Measurement and Attribution)',
        ),
    ),
    AgentSpec(
        name='Data Quality Agent',
        category='governance',
        weight=1.15,
        focus_components=('data_quality', 'cap_rate', 'vacancy'),
        positive='Evidence quality is sufficient for screening analysis.',
        concern='Data quality is not sufficient for institutional approval.',
        action='Replace manual assumptions with source documents and third-party data.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Federal Reserve SR 11-7: Supervisory Guidance on Model Risk Management',
        ),
    ),
    AgentSpec(
        name='Source Reliability Agent',
        category='governance',
        weight=0.9,
        focus_components=('data_quality', 'liquidity', 'market_growth'),
        positive='Source reliability can be improved through data-room controls.',
        concern='Current sources may be biased, stale, or seller-provided.',
        action='Tag every assumption with source, date, owner, and confidence.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Federal Reserve SR 11-7: Supervisory Guidance on Model Risk Management',
        ),
    ),
    AgentSpec(
        name='Model Risk Agent',
        category='governance',
        weight=1.05,
        focus_components=('data_quality', 'dscr', 'cash_on_cash'),
        positive='Model output is interpretable and auditable.',
        concern='Model risk is material because rules and fixtures can mislead.',
        action='Run independent model review, formula tests, and sensitivity sign-off.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Federal Reserve SR 11-7: Supervisory Guidance on Model Risk Management',
        ),
    ),
    AgentSpec(
        name='Fair Housing Compliance Agent',
        category='governance',
        weight=0.7,
        focus_components=('landlord_law', 'data_quality', 'crime'),
        positive='Compliance controls can be established before operations.',
        concern='Screening, advertising, fees, or occupancy standards may create exposure.',
        action='Have counsel review fair-housing, source-of-income, fee, and occupancy policies.',
        role='Institutional diligence workstream: governance',
    ),
    AgentSpec(
        name='Tax Appeal Agent',
        category='governance',
        weight=0.65,
        focus_components=('expense_ratio', 'data_quality', 'liquidity'),
        positive='Tax appeal option can be evaluated after acquisition.',
        concern='Tax reassessment could impair yield if appeal prospects are weak.',
        action='Review comparable assessments, local appeal calendar, and counsel estimates.',
        role='Institutional diligence workstream: governance',
        sources=(
            'IRS Publication 527: Residential Rental Property',
        ),
    ),
    AgentSpec(
        name='Title And Survey Agent',
        category='governance',
        weight=0.75,
        focus_components=('data_quality', 'liquidity', 'rehab_load'),
        positive='Title and survey diligence is a standard closing condition.',
        concern='Title, access, easement, or survey exceptions could block execution.',
        action='Review title commitment, endorsements, survey, access, and encroachments.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 7 (Real Estate Due Diligence Analysis)',
        ),
    ),
    AgentSpec(
        name='Appraisal Review Agent',
        category='governance',
        weight=0.75,
        focus_components=('cap_rate', 'liquidity', 'data_quality'),
        positive='Appraisal support can be reconciled with comps.',
        concern='Appraisal risk may reduce loan proceeds or trigger repricing.',
        action='Review appraiser assumptions, comps, cap rate, income approach, and conditions.',
        role='Institutional diligence workstream: governance',
        sources=(
            'USPAP (The Appraisal Foundation); The Appraisal of Real Estate, 15th ed. (Appraisal Institute)',
        ),
    ),
    AgentSpec(
        name='Insurance Coverage Agent',
        category='governance',
        weight=0.8,
        focus_components=('expense_ratio', 'crime', 'data_quality'),
        positive='Coverage can be defined before closing.',
        concern='Coverage gaps could convert physical risk into equity loss.',
        action='Verify replacement cost, ordinance, liability, flood, wind, and business-interruption coverage.',
        role='Institutional diligence workstream: governance',
    ),
    AgentSpec(
        name='Investment Committee Process Agent',
        category='governance',
        weight=0.85,
        focus_components=('data_quality', 'model_risk', 'risk'),
        positive='The decision can be routed through formal IC controls.',
        concern='IC process lacks documented challenges, dissent, and approval conditions.',
        action='Record committee questions, dissent, approvals, conditions, and post-close covenants.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 11 (Unlisted Real Estate Funds)',
        ),
    ),
    AgentSpec(
        name='Bull Case Agent',
        category='governance',
        weight=0.65,
        focus_components=('cap_rate', 'market_growth', 'liquidity'),
        positive='The upside case is plausible if rent growth and exit liquidity hold.',
        concern='The bull case needs clearer evidence and catalysts.',
        action='Define upside catalysts, milestones, and evidence that would increase conviction.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 1 (Introduction: Risks and Opportunities)',
        ),
    ),
    AgentSpec(
        name='Bear Case Agent',
        category='governance',
        weight=0.95,
        focus_components=('dscr', 'vacancy', 'expense_ratio', 'data_quality'),
        positive='Downside risks are identifiable and can be mitigated.',
        concern='The bear case could overwhelm base-case returns.',
        action='Quantify the downside path that turns this into a capital-loss scenario.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 26 (Real Estate Cycles)',
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 1 (Introduction: Risks and Opportunities)',
        ),
    ),
    AgentSpec(
        name='Portfolio Manager Agent',
        category='governance',
        weight=1.2,
        focus_components=('cap_rate', 'cash_on_cash', 'liquidity', 'data_quality'),
        positive='Portfolio sizing can reflect risk-adjusted conviction.',
        concern='Allocation should be constrained until hard diligence gaps close.',
        action='Set max allocation, reserves, watchlist conditions, and post-close monitoring triggers.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 15 (Building the Portfolio)',
        ),
    ),
    AgentSpec(
        name='Investment Committee Chair Agent',
        category='governance',
        weight=1.35,
        focus_components=('data_quality', 'risk', 'policy', 'cap_rate'),
        positive='The committee can reach a conditional decision with explicit open items.',
        concern='The packet is not ready for unconditional approval.',
        action='Close hard stops, document dissent, and record final approval conditions.',
        role='Institutional diligence workstream: governance',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 15 (Building the Portfolio)',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 10 (DCF and NPV)',
        ),
    ),
    AgentSpec(
        name='After-Tax Returns Agent',
        category='portfolio',
        weight=0.9,
        focus_components=('tax_shield', 'cash_on_cash', 'data_quality'),
        positive='Depreciation meaningfully shelters year-one taxable income.',
        concern='After-tax returns may lag pre-tax returns once depreciation runs thin.',
        action='Model cash flow after taxes with the buyer\'s marginal rate, cost-segregation potential, and exit recapture.',
        sources=(
            'IRS Publication 527: Residential Rental Property',
            'Gallinelli, What Every Real Estate Investor Needs to Know About Cash Flow, Calculation 34: Depreciation',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 14 (After-Tax Investment Analysis)',
        ),
    ),
    AgentSpec(
        name='Market Cycle Agent',
        category='market',
        weight=0.9,
        focus_components=('cycle_position', 'market_growth', 'vacancy'),
        positive='Rent growth is supported by job growth without excess vacancy, consistent with an early-to-mid cycle market.',
        concern='Cycle indicators suggest late-cycle or softening conditions for this market.',
        action='Date the current cycle phase with permits, absorption, and rent-growth trend data before committing to the exit-year assumption.',
        sources=(
            'Linneman & Kirsch, Real Estate Finance & Investments, 5th ed., ch. 26 (Real Estate Cycles)',
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 2 (Global Property Markets and Real Estate Cycles)',
        ),
    ),
    AgentSpec(
        name='Required Return Agent',
        category='portfolio',
        weight=1.0,
        focus_components=('return_spread', 'cap_rate', 'liquidity'),
        positive='Expected total return clears the cost of debt plus an equity risk premium.',
        concern='Expected total return does not clear a risk-premium-based required return at the current basis.',
        action='Build the required return from the risk-free rate plus property risk premia and compare it with cap rate plus realistic growth.',
        sources=(
            'Hartzell & Baum, Real Estate Investment and Finance (Wiley, 2020), ch. 4 (Asset Pricing, Portfolio Theory, and Real Estate)',
            'Geltner, Miller, Clayton & Eichholtz, Commercial Real Estate Analysis and Investments, ch. 22 (Equilibrium Asset Valuation and the Price of Risk)',
        ),
    ),
    AgentSpec(
        name='Lead-Based Paint Agent',
        category='physical',
        weight=0.7,
        focus_components=('lead_paint_era', 'age', 'data_quality'),
        positive='Construction year is outside the pre-1978 lead-based paint disclosure regime.',
        concern='Pre-1978 construction triggers lead-based paint disclosure and likely assessment or abatement costs.',
        action='Confirm the construction year, obtain the lead disclosure, and price inspection or abatement for pre-1978 buildings.',
        sources=(
            'EPA Lead-Based Paint Disclosure Rule (40 CFR Part 745): required for housing built before 1978',
        ),
    ),
    AgentSpec(
        name='Escrow Funding Agent',
        category='debt',
        weight=0.7,
        focus_components=('dscr', 'expense_ratio', 'data_quality'),
        positive='Tax and insurance escrow funding fits within the underwritten expense load.',
        concern='Lender-required tax and insurance escrows may strain monthly cash flow beyond the underwritten expense load.',
        action='Confirm lender escrow requirements for taxes and insurance and reflect impound funding in the monthly cash budget.',
        sources=(
            'Fannie Mae Multifamily Guide Part V \u00a7407: Escrow Requirements for Taxes and Insurance',
        ),
    ),
)
