import type { InstitutionalDecision } from '../types';
import { VerdictBadge } from './Badge';

export function Scorecards({ decision }: { decision: InstitutionalDecision }) {
  const cards = (decision.scorecards ?? []) as Array<{ name?: string; category?: string; score?: number }>;
  return (
    <section className="panel">
      <div className="panel-head"><h2>Category scorecards</h2><span className="hint">weighted workstream scores</span></div>
      <div className="panel-body">
        {cards.map((card, i) => (
          <div key={i} className="scorecard-row">
            <span className="name">{String(card.name ?? card.category)}</span>
            <span className="scorebar">
              <span className="track"><span className="fill" style={{ width: `${Math.min(Number(card.score ?? 0), 100)}%` }} /></span>
              <span className="val">{Number(card.score ?? 0).toFixed(1)}</span>
            </span>
          </div>
        ))}
      </div>
    </section>
  );
}

export function PolicyGates({ decision }: { decision: InstitutionalDecision }) {
  const failed = (decision.policy_results ?? []).filter((r) => !r.passed);
  if (failed.length === 0) return null;
  return (
    <section className="panel">
      <div className="panel-head"><h2>Policy gates</h2><span className="hint">{failed.length} not passing</span></div>
      <div className="panel-body flush">
        <table className="table">
          <thead><tr><th>Gate</th><th className="num">Value</th><th>Finding</th></tr></thead>
          <tbody>
            {failed.map((r, i) => (
              <tr key={i}>
                <td className="strong">{r.limit?.name ?? 'gate'}</td>
                <td className="num">{Number(r.value).toFixed(2)}</td>
                <td>{r.message}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export function AnalystCommentary({ decision }: { decision: InstitutionalDecision }) {
  const review = decision.llm_review;
  if (!review || review.opinions.length === 0) return null;
  return (
    <section className="panel">
      <div className="panel-head">
        <h2>Analyst debate</h2>
        <span className="hint">generated by {review.model} · scores above are not model-generated</span>
      </div>
      <div className="panel-body flush">
        {review.opinions.map((opinion) => (
          <details key={opinion.analyst} className="findings-group" open={opinion.analyst === 'IC Chair'}>
            <summary><span>{opinion.analyst}</span><span className="meta"><span className="chev">›</span></span></summary>
            <div className="opinion">
              <p className="thesis-full">{opinion.thesis}</p>
              <ul>
                {opinion.key_points.map((point, i) => <li key={i}>{point}</li>)}
              </ul>
              {opinion.questions.length > 0 && (
                <p className="questions"><strong>Open questions:</strong> {opinion.questions.join(' ')}</p>
              )}
            </div>
          </details>
        ))}
        {review.errors.length > 0 && <div className="error-note" style={{ margin: 'var(--s3) var(--s5)' }}>{review.errors.join('; ')}</div>}
      </div>
    </section>
  );
}

export function VerdictHeader({ decision }: { decision: InstitutionalDecision }) {
  const metrics = decision.metrics ?? {};
  const pct = (v: unknown) => (v == null ? 'n/a' : `${(Number(v) * 100).toFixed(1)}%`);
  const hardStops = decision.hard_stops?.length ?? 0;
  return (
    <section className="verdict" aria-label="Committee verdict">
      <VerdictBadge value={String(decision.recommendation)} large />
      <div className="figure"><span className="label">Overall score</span><span className="value">{decision.overall_score.toFixed(1)}<span className="unit">/100</span></span></div>
      <div className="figure"><span className="label">Cap rate</span><span className="value">{pct(metrics.cap_rate)}</span></div>
      <div className="figure"><span className="label">DSCR</span><span className="value">{metrics.dscr == null ? 'n/a' : `${Number(metrics.dscr).toFixed(2)}x`}</span></div>
      <div className="figure"><span className="label">Hard stops</span><span className="value">{hardStops}</span></div>
    </section>
  );
}
